name: GithubActions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug

      - name: Run Tests
        run: dotnet test --no-build --configuration Debug --logger "console;verbosity=detailed"

#      - name: Publish
#        run: dotnet publish --no-build --configuration Release --output publish

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          args: "-tt -vvv"