name: GithubActions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug

      - name: Run Tests
        run: dotnet test --no-build --configuration Debug --logger "console;verbosity=detailed"

#      - name: Publish
#        run: dotnet publish --no-build --configuration Release --output publish

      - run: |
          whoami
          
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_URL_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!
            webhookUrl: ${{ secrets.DISCORD_URL_WEBHOOK }}
      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
            severity: warn
            details: Test Cancelled!
            webhookUrl: ${{ secrets.DISCORD_URL_WEBHOOK }}